<Project>

  <!-- Workaround for XamlPreCompile compilation errors -->
  <Target Name="SpecifyVBRuntimeForXamlPreCompile" BeforeTargets="XamlPreCompile">
    <PropertyGroup>
      <VBRuntime>None</VBRuntime>
    </PropertyGroup>
  </Target>
  
  <!-- Load the app runtime without MSIX packaging -->
  <PropertyGroup Condition="'$(WindowsAppSDKSelfContained)'=='true'">
    <WindowsAppSdkAutoInitialize>false</WindowsAppSdkAutoInitialize>
    <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(WindowsAppSDKSelfContained)'=='true'">
    <Compile Include="$(MSBuildThisFileDirectory)include\UndockedRegFreeWinRTAutoInitializer.vb" LinkBase="My Project"/>
  </ItemGroup>

</Project>
