' <auto-generated>
' Exclude this file from StyleCop analysis. This file isn't generated but is added to projects.
' DO Not MODIFY. Changes to this file may cause incorrect behavior And will be lost on updates.
' </auto-generated>

Partial Module Program
    Declare Unicode Function WindowsAppRuntime_EnsureIsLoaded Lib "Microsoft.WindowsAppRuntime.dll" () As Integer

    Sub New()
        Environment.SetEnvironmentVariable("MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY", AppContext.BaseDirectory)
        WindowsAppRuntime_EnsureIsLoaded
    End Sub

End Module
